# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosmos.proto',
  package='cosmos.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63osmos.proto\x12\x0f\x63osmos.protobuf\"\x83\x03\n\x06Person\x12\n\n\x02Id\x18\x01 \x01(\x0c\x12\x30\n\x04type\x18\x02 \x01(\x0e\x32\".cosmos.protobuf.Person.PersonType\x12\x0f\n\x07inGroup\x18\x03 \x01(\x08\x12\x0f\n\x07\x64\x65leted\x18\x04 \x01(\x08\x12,\n\x05point\x18\x05 \x01(\x0b\x32\x1d.cosmos.protobuf.Person.Point\x12\x34\n\tdirection\x18\x06 \x01(\x0e\x32!.cosmos.protobuf.Person.Direction\x1a\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"b\n\nPersonType\x12\x0b\n\x07\x43ITIZEN\x10\x00\x12\x08\n\x04HERO\x10\x01\x12\n\n\x06WIZARD\x10\x02\x12\x0b\n\x07MONSTER\x10\x03\x12\r\n\tNECROMANT\x10\x04\x12\n\n\x06\x44RAGON\x10\x05\x12\t\n\x05GROUP\x10\x06\"2\n\tDirection\x12\x08\n\x04\x44OWN\x10\x00\x12\x06\n\x02UP\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x08\n\x04LEFT\x10\x03\"2\n\x07Persons\x12\'\n\x06person\x18\x01 \x03(\x0b\x32\x17.cosmos.protobuf.PersonB\x1f\xaa\x02\x1cTelegram.Bot.Cosmos.Protobufb\x06proto3')
)



_PERSON_PERSONTYPE = _descriptor.EnumDescriptor(
  name='PersonType',
  full_name='cosmos.protobuf.Person.PersonType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CITIZEN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HERO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WIZARD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONSTER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NECROMANT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAGON', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUP', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=271,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_PERSON_PERSONTYPE)

_PERSON_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='cosmos.protobuf.Person.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=371,
  serialized_end=421,
)
_sym_db.RegisterEnumDescriptor(_PERSON_DIRECTION)


_PERSON_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='cosmos.protobuf.Person.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='cosmos.protobuf.Person.Point.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='cosmos.protobuf.Person.Point.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=269,
)

_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='cosmos.protobuf.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='cosmos.protobuf.Person.Id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='cosmos.protobuf.Person.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inGroup', full_name='cosmos.protobuf.Person.inGroup', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='cosmos.protobuf.Person.deleted', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point', full_name='cosmos.protobuf.Person.point', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='cosmos.protobuf.Person.direction', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PERSON_POINT, ],
  enum_types=[
    _PERSON_PERSONTYPE,
    _PERSON_DIRECTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=421,
)


_PERSONS = _descriptor.Descriptor(
  name='Persons',
  full_name='cosmos.protobuf.Persons',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='cosmos.protobuf.Persons.person', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=473,
)

_PERSON_POINT.containing_type = _PERSON
_PERSON.fields_by_name['type'].enum_type = _PERSON_PERSONTYPE
_PERSON.fields_by_name['point'].message_type = _PERSON_POINT
_PERSON.fields_by_name['direction'].enum_type = _PERSON_DIRECTION
_PERSON_PERSONTYPE.containing_type = _PERSON
_PERSON_DIRECTION.containing_type = _PERSON
_PERSONS.fields_by_name['person'].message_type = _PERSON
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Persons'] = _PERSONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(

  Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
    DESCRIPTOR = _PERSON_POINT,
    __module__ = 'cosmos_pb2'
    # @@protoc_insertion_point(class_scope:cosmos.protobuf.Person.Point)
    ))
  ,
  DESCRIPTOR = _PERSON,
  __module__ = 'cosmos_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.protobuf.Person)
  ))
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.Point)

Persons = _reflection.GeneratedProtocolMessageType('Persons', (_message.Message,), dict(
  DESCRIPTOR = _PERSONS,
  __module__ = 'cosmos_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.protobuf.Persons)
  ))
_sym_db.RegisterMessage(Persons)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\034Telegram.Bot.Cosmos.Protobuf'))
# @@protoc_insertion_point(module_scope)
